ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS address_entrance VARCHAR(20) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS address_floor VARCHAR(20) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS comment TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS delivery_service VARCHAR(50) NOT NULL DEFAULT 'courier';