ALTER TABLE service_items ADD COLUMN IF NOT EXISTS image_url TEXT NOT NULL DEFAULT '';
ALTER TABLE service_items ADD COLUMN IF NOT EXISTS discount VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE service_items ADD COLUMN IF NOT EXISTS duration VARCHAR(64) NOT NULL DEFAULT '';